/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comumanager.view;

import comumanager.view.consulta.ViewConAnexo;
import comumanager.view.consulta.ViewConPergunta;
import comumanager.view.consulta.ViewConComunidade;
import comumanager.view.consulta.ViewConEntrevistado;
import comumanager.view.consulta.ViewConPesquisa;
import comumanager.view.consulta.ViewConQuestionario;
import comumanager.view.consulta.ViewConResposta;

/**
 *
 * @author lucas
 */
public class ViewConsulta extends javax.swing.JPanel {

    /**
     * Creates new form ViewConsulta
     */
    public ViewConsulta() {
        initComponents();
        jTabbedPane1.addTab("Pesquisa", new ViewConPesquisa());
        jTabbedPane1.addTab("Questionário", new ViewConQuestionario());
        jTabbedPane1.addTab("Comunidade", new ViewConComunidade());
        jTabbedPane1.addTab("Entrevistado", new ViewConEntrevistado());
        jTabbedPane1.addTab("Pergunta", new ViewConPergunta());
        jTabbedPane1.addTab("Resposta", new ViewConResposta());
        jTabbedPane1.addTab("Anexo", new ViewConAnexo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        jTabbedPane1.setBackground(java.awt.Color.white);
        jTabbedPane1.setFont(new java.awt.Font("Fira Sans", 0, 15)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
